#!/usr/bin/env python3
"""Extract IQ codebook tables from the pinned llama.cpp checkout (vendor/PIN)
into src/quants_grids.h. Stdlib-only; dev-time only (the generated header is
committed). Handles both plain `static const T name[N] = {...};` initializers
and ggml-common.h's `GGML_TABLE_BEGIN(T, name, N) ... GGML_TABLE_END()` form.

Usage: python3 tools/make_quant_grids.py
"""
import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
VENDOR = REPO / "vendor" / "llama.cpp"
OUT = REPO / "src" / "quants_grids.h"

TABLES = [  # (name, c_type, expected_count)
    ("iq2xs_grid", "uint64_t", 512),
    ("iq3xxs_grid", "uint32_t", 256),
    ("ksigns_iq2xs", "uint8_t", 128),
    ("kmask_iq2xs", "uint8_t", 8),
    ("kvalues_iq4nl", "int8_t", 16),
]
SOURCES = [
    VENDOR / "ggml" / "src" / "ggml-common.h",
    VENDOR / "ggml" / "src" / "ggml-quants.c",
]

def find_table(name):
    pat_plain = re.compile(
        r"static\s+const\s+\w+\s+" + name + r"\s*\[\s*\w*\s*\]\s*=\s*\{(.*?)\};", re.S)
    pat_ggml = re.compile(
        r"GGML_TABLE_BEGIN\(\s*\w+\s*,\s*" + name + r"\s*,\s*\d+\s*\)(.*?)GGML_TABLE_END\(\)", re.S)
    for src in SOURCES:
        if not src.exists():
            continue
        text = src.read_text()
        m = pat_ggml.search(text) or pat_plain.search(text)
        if m:
            body = m.group(1)
            vals = [v for v in re.split(r"[,\s]+", body) if v and not v.startswith("//")]
            return vals, src
    raise SystemExit(f"make_quant_grids: table {name} not found in {[str(s) for s in SOURCES]}")

def main():
    if not VENDOR.exists():
        raise SystemExit("make_quant_grids: vendor/llama.cpp missing; see vendor/PIN")
    commit = subprocess.run(["git", "-C", str(VENDOR), "rev-parse", "HEAD"],
                            capture_output=True, text=True, check=True).stdout.strip()
    lines = [
        "/* Generated by tools/make_quant_grids.py — do not edit by hand.",
        f" * Source: llama.cpp/ggml (MIT, see NOTICE), commit {commit} (vendor/PIN).",
        " * IQ-quant codebook tables required by src/quants.c. */",
        "#ifndef SEPIA_QUANTS_GRIDS_H",
        "#define SEPIA_QUANTS_GRIDS_H",
        "#include <stdint.h>",
        "",
    ]
    for name, ctype, count in TABLES:
        vals, src = find_table(name)
        if len(vals) != count:
            raise SystemExit(f"make_quant_grids: {name}: expected {count} values, got {len(vals)} ({src})")
        lines.append(f"static const {ctype} {name}[{count}] = {{")
        for i in range(0, count, 8):
            lines.append("    " + ", ".join(vals[i:i + 8]) + ",")
        lines.append("};")
        lines.append("")
        print(f"{name}: {count} values from {src.relative_to(REPO)}")
    lines.append("#endif")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(REPO)}")

def _selftest():
    pass

if __name__ == "__main__":
    main()
