#!/usr/bin/env python3
"""Generate src/unicode_tables.h: sorted codepoint ranges with a class bitmask.
Classes cover exactly what the o200k-family pre-tokenizer regex needs.
Stdlib-only (unicodedata); the generated header is committed.
Usage: python3 tools/make_unicode_tables.py
"""
import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "unicode_tables.h"

# [Amended 2026-07-20: the extracted inkling regex (docs/tokenizer-pre-regex.txt) is
# llama.cpp's lookahead formulation — its letter classes are (L|M) minus ASCII case
# ranges, so only four coarse classes are needed, not the five-way Lu/Ll/Lm/Lo split.]
UC_L, UC_M, UC_N, UC_WS = 1, 2, 4, 8
# Unicode White_Space property (PropList.txt), NOT Python str.isspace():
WHITESPACE = ([0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20, 0x85, 0xA0, 0x1680]
              + list(range(0x2000, 0x200B)) + [0x2028, 0x2029, 0x202F, 0x205F, 0x3000])

def classify(cp):
    mask = 0
    cat = unicodedata.category(chr(cp))
    if cat.startswith("L"): mask |= UC_L
    elif cat.startswith("M"): mask |= UC_M
    elif cat.startswith("N"): mask |= UC_N
    if cp in WS_SET: mask |= UC_WS
    return mask

WS_SET = set(WHITESPACE)

def main():
    ranges = []
    prev_mask, start = 0, 0
    for cp in range(0x110000):
        m = classify(cp)
        if m != prev_mask:
            if prev_mask:
                ranges.append((start, cp - 1, prev_mask))
            start, prev_mask = cp, m
    if prev_mask:
        ranges.append((start, 0x10FFFF, prev_mask))
    with open(OUT, "w") as f:
        f.write("/* Generated by tools/make_unicode_tables.py (Python %s, unicodedata %s).\n"
                " * Codepoint ranges -> class bitmask for the pre-tokenizer scanner. */\n"
                % (sys.version.split()[0], unicodedata.unidata_version))
        f.write("#ifndef SEPIA_UNICODE_TABLES_H\n#define SEPIA_UNICODE_TABLES_H\n")
        f.write("#include <stdint.h>\n")
        f.write("enum { UC_L=1, UC_M=2, UC_N=4, UC_WS=8 };\n")
        f.write("typedef struct { uint32_t lo, hi; uint8_t mask; } UcRange;\n")
        f.write("static const UcRange uc_ranges[] = {\n")
        for lo, hi, m in ranges:
            f.write("    {0x%X, 0x%X, %d},\n" % (lo, hi, m))
        f.write("};\n")
        f.write("static const uint32_t uc_n_ranges = %d;\n#endif\n" % len(ranges))
    print(f"wrote {OUT} ({len(ranges)} ranges)")

if __name__ == "__main__":
    main()
