#!/usr/bin/env python3
"""Convert src/quants_grids.h's IQ codebook tables into MSL `constant` arrays
so metal/matvec_q.metal's IQ2_XS/IQ3_XXS/IQ4_XS kernels can index them
directly. Stdlib-only, deterministic (pure text transform of the committed
header -- no filesystem globbing, no timestamps, no external commands), does
NOT modify src/quants_grids.h.

Usage: python3 tools/make_msl_grids.py
"""
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src" / "quants_grids.h"
OUT = REPO / "metal" / "00_quants_grids.metal"

# (C name, C type, MSL type, element count, per-value literal suffix).
# Order matches src/quants_grids.h's declaration order.
TABLES = [
    ("iq2xs_grid",    "uint64_t", "ulong", 512, "UL"),
    ("iq3xxs_grid",   "uint32_t", "uint",  256, "u"),
    ("ksigns_iq2xs",  "uint8_t",  "uchar", 128, ""),
    ("kmask_iq2xs",   "uint8_t",  "uchar", 8,   ""),
    ("kvalues_iq4nl", "int8_t",   "char",  16,  ""),
]


def read_provenance(text):
    """Pull the leading /* ... */ comment block out of quants_grids.h verbatim
    (it already records the llama.cpp vendor commit) so this generated file
    cites the same provenance without re-invoking git."""
    m = re.match(r"\s*/\*(.*?)\*/", text, re.S)
    if not m:
        raise SystemExit("make_msl_grids: no leading /* ... */ comment in quants_grids.h")
    lines = [ln.strip() for ln in m.group(1).splitlines()]
    return [ln for ln in lines if ln]


def find_table(text, name):
    pat = re.compile(
        r"static\s+const\s+\w+\s+" + re.escape(name) + r"\s*\[\s*\d*\s*\]\s*=\s*\{(.*?)\};", re.S)
    m = pat.search(text)
    if not m:
        raise SystemExit(f"make_msl_grids: table {name} not found in {SRC}")
    body = m.group(1)
    vals = [v for v in re.split(r"[,\s]+", body) if v]
    return vals


def main():
    if not SRC.exists():
        raise SystemExit(f"make_msl_grids: {SRC} missing")
    text = SRC.read_text()
    provenance = read_provenance(text)

    lines = [
        "// metal/00_quants_grids.metal -- MSL `constant`-address-space codebook",
        "// tables for the IQ2_XS/IQ3_XXS/IQ4_XS dequant kernels (Task 6).",
        "// GENERATED by tools/make_msl_grids.py from src/quants_grids.h -- do not",
        "// edit by hand; re-run the generator if the source header changes.",
        "//",
        "// Provenance (copied from src/quants_grids.h's own header):",
    ]
    lines += [f"//   {ln}" for ln in provenance]
    lines += [
        "//",
        "// Filename note: sepia_gpu_load_source (src/sepia_metal.m) concatenates",
        "// every metal/*.metal file into one newLibraryWithSource: translation",
        "// unit, sorted alphabetically by filename. The \"00_\" prefix here is",
        "// the whole mechanism -- it places this file's `constant` array",
        "// DEFINITIONS before metal/matvec_q.metal in the concatenated source,",
        "// so matvec_q.metal's IQ unpack functions can reference iq2xs_grid /",
        "// iq3xxs_grid / ksigns_iq2xs / kmask_iq2xs / kvalues_iq4nl directly --",
        "// no forward declaration needed (contrast matvec_q.metal's own",
        "// sepia_tg_reduce_sum prototype, needed only because ops.metal, where",
        "// that helper is DEFINED, sorts AFTER matvec_q.metal). Simplest",
        "// mechanism consistent with the existing loader: no shim changes, no",
        "// #include machinery, just filename ordering doing the concatenation's",
        "// job.",
        "#include <metal_stdlib>",
        "using namespace metal;",
        "",
    ]

    for name, ctype, msl_type, count, suffix in TABLES:
        vals = find_table(text, name)
        if len(vals) != count:
            raise SystemExit(f"make_msl_grids: {name}: expected {count} values, got {len(vals)}")
        lines.append(f"// {name}: {ctype}[{count}] in src/quants_grids.h.")
        lines.append(f"constant {msl_type} {name}[{count}] = {{")
        for i in range(0, count, 8):
            row = ", ".join(f"{v}{suffix}" for v in vals[i:i + 8])
            lines.append(f"    {row},")
        lines.append("};")
        lines.append("")
        print(f"{name}: {count} values -> {msl_type}[{count}]")

    OUT.write_text("\n".join(lines).rstrip("\n") + "\n")
    print(f"wrote {OUT.relative_to(REPO)}")


def _selftest():
    pass


if __name__ == "__main__":
    main()
